### ISSUE TITLE
I get this error when I uninstall the module and I go in 

### ISSUE THREAD

**Issue by lapagept** [OCA/account-invoicing#121]
Hello there,
When I install the module, then I go in settings -> Configuration -> Invoicing, all is right and I see the new fields from your module.
But when I after uninstall the module, and after I go in settings -> Configuration -> Invoicing, get this error :::

```
Traceback (most recent call last):
  File "/home/odoo-test/odoo-8.0-20151203/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo-test/odoo-8.0-20151203/openerp/http.py", line 574, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo-test/odoo-8.0-20151203/openerp/http.py", line 310, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo-test/odoo-8.0-20151203/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo-test/odoo-8.0-20151203/openerp/http.py", line 307, in checked_call
    return self.endpoint(*a, **kw)
  File "/home/odoo-test/odoo-8.0-20151203/openerp/http.py", line 803, in __call__
    return self.method(*args, **kw)
  File "/home/odoo-test/odoo-8.0-20151203/openerp/http.py", line 403, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo-test/odoo-8.0-20151203/openerp/addons/web/controllers/main.py", line 944, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/odoo-test/odoo-8.0-20151203/openerp/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/home/odoo-test/odoo-8.0-20151203/openerp/api.py", line 256, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/odoo-test/odoo-8.0-20151203/openerp/api.py", line 387, in old_api
    result = method(recs, *args, **kwargs)
  File "/home/odoo-test/odoo-8.0-20151203/openerp/models.py", line 5957, in onchange
    record._onchange_eval(name, field_onchange[name], result)
  File "/home/odoo-test/odoo-8.0-20151203/openerp/models.py", line 5870, in _onchange_eval
    self.update(self._convert_to_cache(method_res['value'], validate=False))
  File "/home/odoo-test/odoo-8.0-20151203/openerp/models.py", line 5468, in update
    self[name] = value
  File "/home/odoo-test/odoo-8.0-20151203/openerp/models.py", line 5650, in __setitem__
    return self._fields[key].__set__(self, value)
  File "/home/odoo-test/odoo-8.0-20151203/openerp/fields.py", line 835, in __set__
    value = self.convert_to_cache(value, record)
  File "/home/odoo-test/odoo-8.0-20151203/openerp/fields.py", line 1404, in convert_to_cache
    raise ValueError("Wrong value for %s: %r" % (self, value))
ValueError: Wrong value for account.config.settings.tax_calculation_rounding_method: u'swedish_add_invoice_line'
```

**Comment by lapagept** [comment]
In the res.company table, I had the value "swedish_add_invoice_line" in the "tax_calculation_rounding_method". I have deleted this value, an now, I can click on settings -> Configuration -> Invoicing without any error.
