### ISSUE TITLE
14.0 account_invoice_pricelist test failures

### ISSUE THREAD

**Issue by gdgellatly** [OCA/account-invoicing#1220]
## Module
Account Invoice Pricelist

## Describe the bug
Tests failing. No further investigation yet

## To Reproduce
**Affected versions**: 14.0

1. Run tests on repo

**Expected behavior**
Green

**Additional context**
```
2022-08-18 23:23:37,463 255 INFO odoo odoo.addons.account_invoice_pricelist.tests.test_account_move_pricelist: Starting TestAccountMovePricelist.test_account_invoice_change_pricelist ... 
2022-08-18 23:23:37,630 255 INFO odoo odoo.addons.account_invoice_pricelist.tests.test_account_move_pricelist: Starting TestAccountMovePricelist.test_account_invoice_fixed_pricelist_with_discount_secondary_currency ... 
2022-08-18 23:23:37,818 255 INFO odoo odoo.addons.account_invoice_pricelist.tests.test_account_move_pricelist: Starting TestAccountMovePricelist.test_account_invoice_fixed_pricelist_without_discount_secondary_currency ... 
2022-08-18 23:23:37,997 255 INFO odoo odoo.addons.account_invoice_pricelist.tests.test_account_move_pricelist: ====================================================================== 
2022-08-18 23:23:37,998 255 ERROR odoo odoo.addons.account_invoice_pricelist.tests.test_account_move_pricelist: FAIL: TestAccountMovePricelist.test_account_invoice_fixed_pricelist_without_discount_secondary_currency
Traceback (most recent call last):
  File "/__w/account-invoicing/account-invoicing/account_invoice_pricelist/tests/test_account_move_pricelist.py", line 311, in test_account_invoice_fixed_pricelist_without_discount_secondary_currency
    self.assertAlmostEqual(invoice_line.price_unit, 65.41)
AssertionError: 100.0 != 65.41 within 7 places
 
2022-08-18 23:23:37,998 255 INFO odoo odoo.addons.account_invoice_pricelist.tests.test_account_move_pricelist: Starting TestAccountMovePricelist.test_account_invoice_pricelist ... 
2022-08-18 23:23:38,014 255 INFO odoo odoo.addons.account_invoice_pricelist.tests.test_account_move_pricelist: Starting TestAccountMovePricelist.test_account_invoice_pricelist_with_discount_secondary_currency ... 
2022-08-18 23:23:38,207 255 INFO odoo odoo.addons.account_invoice_pricelist.tests.test_account_move_pricelist: ====================================================================== 
2022-08-18 23:23:38,207 255 ERROR odoo odoo.addons.account_invoice_pricelist.tests.test_account_move_pricelist: FAIL: TestAccountMovePricelist.test_account_invoice_pricelist_with_discount_secondary_currency
Traceback (most recent call last):
  File "/__w/account-invoicing/account-invoicing/account_invoice_pricelist/tests/test_account_move_pricelist.py", line 287, in test_account_invoice_pricelist_with_discount_secondary_currency
    self.assertAlmostEqual(invoice_line.price_unit, 58.87)
AssertionError: 90.0 != 58.87 within 7 places
 
2022-08-18 23:23:38,207 255 INFO odoo odoo.addons.account_invoice_pricelist.tests.test_account_move_pricelist: Starting TestAccountMovePricelist.test_account_invoice_pricelist_without_discount ... 
2022-08-18 23:23:38,366 255 INFO odoo odoo.addons.account_invoice_pricelist.tests.test_account_move_pricelist: Starting TestAccountMovePricelist.test_account_invoice_pricelist_without_discount_secondary_currency ... 
2022-08-18 23:23:38,553 255 INFO odoo odoo.addons.account_invoice_pricelist.tests.test_account_move_pricelist: ====================================================================== 
2022-08-18 23:23:38,553 255 ERROR odoo odoo.addons.account_invoice_pricelist.tests.test_account_move_pricelist: FAIL: TestAccountMovePricelist.test_account_invoice_pricelist_without_discount_secondary_currency
Traceback (most recent call last):
  File "/__w/account-invoicing/account-invoicing/account_invoice_pricelist/tests/test_account_move_pricelist.py", line 295, in test_account_invoice_pricelist_without_discount_secondary_currency
    self.assertAlmostEqual(invoice_line.price_unit, 65.41)
AssertionError: 100.0 != 65.41 within 7 places
 
2022-08-18 23:23:38,553 255 INFO odoo odoo.addons.account_invoice_pricelist.tests.test_account_move_pricelist: Starting TestAccountMovePricelist.test_account_invoice_with_discount_change_pricelist ... 
2022-08-18 23:23:38,742 255 INFO odoo odoo.addons.account_invoice_pricelist.tests.test_account_move_pricelist: Starting TestAccountMovePricelist.test_account_invoice_without_discount_change_pricelist ... 
2022-08-18 23:23:38,920 255 INFO odoo odoo.addons.account_invoice_pricelist.tests.test_account_move_pricelist: Starting TestAccountMovePricelist.test_upstream_file_hash ... 
2022-08-18 23:23:39,312 255 INFO odoo odoo.modules.loading: Module account_invoice_pricelist loaded in 2.83s (incl. 1.93s test), [195](https://github.com/OCA/account-invoicing/runs/7909049930?check_suite_focus=true#step:8:196) queries (+1667 test) 
[202](https://github.com/OCA/account-invoicing/runs/7909049930?check_suite_focus=true#step:8:203)2-08-18 23:23:39,312 255 ERROR odoo odoo.modules.loading: Module account_invoice_pricelist: 3 failures, 0 errors of 10 tests
```

**Comment by gdgellatly** [comment]
Latest tests green, no idea

**Comment by gdgellatly** [comment]
Now red again. Wow this is some issue. Loading order?

**Comment by pedrobaeza** [comment]
I think this has to be with the execution hour, as if it's around midnight, timezone glitches happen.
