### ISSUE TITLE
AttributeError: 'tuple' object has no attribute 'keys' when merging two invoices

### ISSUE THREAD

**Issue by sebytza05** [OCA/account-invoicing#221]
Hello guys,
I recieved this error when i try to merge 2 invoices, can you please help me solve this issue.

Traceback (most recent call last):
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_a2115ef-py2.7.egg/openerp/http.py", line 517, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_a2115ef-py2.7.egg/openerp/http.py", line 538, in dispatch
    result = self._call_function(**self.params)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_a2115ef-py2.7.egg/openerp/http.py", line 294, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_a2115ef-py2.7.egg/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_a2115ef-py2.7.egg/openerp/http.py", line 291, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_a2115ef-py2.7.egg/openerp/http.py", line 754, in __call__
    return self.method(*args, **kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_a2115ef-py2.7.egg/openerp/http.py", line 387, in response_wrap
    response = f(*args, **kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_a2115ef-py2.7.egg/openerp/addons/web/controllers/main.py", line 953, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_a2115ef-py2.7.egg/openerp/addons/web/controllers/main.py", line 941, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_a2115ef-py2.7.egg/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_a2115ef-py2.7.egg/openerp/api.py", line 360, in old_api
    result = method(recs, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_a2115ef-py2.7.egg/openerp/addons/account_invoice_merge/wizard/invoice_merge.py", line 96, in merge_invoices
    'domain': [('id', 'in', ids + allinvoices.keys())],
AttributeError: 'tuple' object has no attribute 'keys'

**Comment by antoniocanovas** [comment]
Same error for me.
Any idea?

**Comment by soinel** [comment]
I am in the same case.
Have you solved it?


Odoo Server Error
Traceback (most recent call last):
  File "/opt/admin/admin-server/openerp/http.py", line 544, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/admin/admin-server/openerp/http.py", line 581, in dispatch
    result = self._call_function(**self.params)
  File "/opt/admin/admin-server/openerp/http.py", line 317, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/admin/admin-server/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/admin/admin-server/openerp/http.py", line 314, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/admin/admin-server/openerp/http.py", line 810, in __call__
    return self.method(*args, **kw)
  File "/opt/admin/admin-server/openerp/http.py", line 410, in response_wrap
    response = f(*args, **kw)
  File "/opt/admin/admin-server/addons/web/controllers/main.py", line 948, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/admin/admin-server/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/admin/admin-server/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/admin/admin-server/openerp/api.py", line 399, in old_api
    result = method(recs, *args, **kwargs)
  File "/opt/admin/admin-server/openerp/addons/account_invoice_merge/wizard/invoice_merge.py", line 96, in merge_invoices
    'domain': [('id', 'in', ids + allinvoices.keys())],
AttributeError: 'tuple' object has no attribute 'keys'

**Comment by pedrobaeza** [comment]
Is this still happening with latest version?

**Comment by sebytza05** [comment]
Yea, it is still happening or i do something wrong.

**Comment by danielduqma** [comment]
I'm also having this problem with latest commit from branch 8.0

**Comment by thomich** [comment]
for your records.. and if anyone will solve it here:

![selection_001](https://cloud.githubusercontent.com/assets/4398840/25660351/1dd84496-300c-11e7-88f5-765174ee8929.png)

why not doing a PR? cause there are 23 [8.0] PR's still open and seams this module is just waiting for end of life...
