### ISSUE TITLE
[10.0] [account_invoice_merge] ERROR

### ISSUE THREAD

**Issue by diegovegatedra** [OCA/account-invoicing#364]
Hi,
I have installed account_invoice_merge plugin, but when I try to merge two invoices it doesn't work and I don't know why. I was looking for information about this issue but have find anything.

I put here the Traceback of the error:

2018-03-09 08:44:23,787 10763 ERROR produccion odoo.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 677, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 333, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 326, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 935, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 506, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/site-packages/odoo/addons/web/controllers/main.py", line 889, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/python2.7/site-packages/odoo/addons/web/controllers/main.py", line 877, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python2.7/site-packages/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python2.7/site-packages/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/var/lib/odoo/addons/10.0/modulos_OCA/account_invoice_merge_attachment/wizards/invoice_merge.py", line 18, in merge_invoices
    link_attachment=self.link_attachment
  File "/var/lib/odoo/addons/10.0/modulos_OCA/account_invoice_merge/wizard/invoice_merge.py", line 89, in merge_invoices
    date_invoice=self.date_invoice)
  File "/var/lib/odoo/addons/10.0/modulos_OCA/account_invoice_merge_attachment/models/account_invoice.py", line 15, in do_merge
    keep_references=keep_references, date_invoice=date_invoice)
  File "/var/lib/odoo/addons/10.0/modulos_OCA/account_invoice_merge/models/account_invoice.py", line 181, in do_merge
    newinvoice = self.with_context(is_merge=True).create(invoice_data)
  File "/var/lib/odoo/addons/10.0/customized_invoice/models/invoice.py", line 46, in create
    res = super(InvoiceTemplates, self).create(vals)
  File "/var/lib/odoo/addons/10.0/modulos_OCA/account_banking_mandate/models/account_invoice.py", line 50, in create
    return super(AccountInvoice, self).create(vals)
  File "/usr/lib/python2.7/site-packages/odoo/addons/purchase/models/account_invoice.py", line 199, in create
    invoice = super(AccountInvoice, self).create(vals)
  File "/var/lib/odoo/addons/10.0/modulos_OCA/account_payment_partner/models/account_invoice.py", line 62, in create
    return super(AccountInvoice, self).create(vals)
  File "/usr/lib/python2.7/site-packages/odoo/addons/account/models/account_invoice.py", line 346, in create
    invoice = super(AccountInvoice, self.with_context(mail_create_nolog=True)).create(vals)
  File "/usr/lib/python2.7/site-packages/odoo/addons/mail/models/mail_thread.py", line 228, in create
    thread = super(MailThread, self).create(values)
  File "/usr/lib/python2.7/site-packages/odoo/models.py", line 3803, in create
    vals = self._add_missing_default_values(vals)
  File "/usr/lib/python2.7/site-packages/odoo/models.py", line 1635, in _add_missing_default_values
    defaults = self.default_get(list(missing_defaults))
  File "/usr/lib/python2.7/site-packages/odoo/addons/utm/models/utm.py", line 61, in default_get
    values = super(UtmMixin, self).default_get(fields)
  File "/usr/lib/python2.7/site-packages/odoo/models.py", line 1118, in default_get
    defaults[name] = field.default(self)
  File "/var/lib/odoo/addons/10.0/customized_invoice/models/invoice.py", line 52, in <lambda>
    style = fields.Many2one('report.template.settings', 'Invoice Style', help="Select Style to use when printing this invoice", default= lambda self: self.partner_id.style or self.env.user.company_id.default_style)
  File "/usr/lib/python2.7/site-packages/odoo/fields.py", line 904, in __get__
    record.ensure_one()
  File "/usr/lib/python2.7/site-packages/odoo/models.py", line 4820, in ensure_one
    raise ValueError("Expected singleton: %s" % self)
ValueError: Expected singleton: account.invoice(403, 402)

Someone can help me with this issue?
Thanks in advance!

**Comment by pedrobaeza** [comment]
First time you init your DB, you have to select a template for your invoices. Please do that before merging.
