### ISSUE TITLE
KeyError: False

### ISSUE THREAD

**Issue by digitalliuzg** [OCA/account-invoicing#574]
Traceback (most recent call last):
  File "E:\odoo\ocb\odoo\http.py", line 642, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "E:\odoo\ocb\odoo\http.py", line 684, in dispatch
    result = self._call_function(**self.params)
  File "E:\odoo\ocb\odoo\http.py", line 334, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "E:\odoo\ocb\odoo\service\model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "E:\odoo\ocb\odoo\http.py", line 327, in checked_call
    result = self.endpoint(*a, **kw)
  File "E:\odoo\ocb\odoo\http.py", line 942, in __call__
    return self.method(*args, **kw)
  File "E:\odoo\ocb\odoo\http.py", line 507, in response_wrap
    response = f(*args, **kw)
  File "E:\odoo\OCB\addons\web\controllers\main.py", line 899, in call_button
    action = self._call_kw(model, method, args, {})
  File "E:\odoo\OCB\addons\web\controllers\main.py", line 887, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "E:\odoo\ocb\odoo\api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "E:\odoo\ocb\odoo\api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "E:\odoo\source\ocaaddons\account-invoicing\stock_picking_invoicing\wizards\stock_invoice_onshipping.py", line 212, in action_generate
    invoices = self._action_generate_invoices()
  File "E:\odoo\source\ocaaddons\account-invoicing\stock_picking_invoicing\wizards\stock_invoice_onshipping.py", line 488, in _action_generate_invoices
    line_values = self._get_invoice_line_values(moves, invoice)
  File "E:\odoo\source\ocaaddons\account-invoicing\stock_picking_invoicing\wizards\stock_invoice_onshipping.py", line 457, in _get_invoice_line_values
    values = self._simulate_invoice_line_onchange(values)
  File "E:\odoo\source\ocaaddons\account-invoicing\stock_picking_invoicing\wizards\stock_invoice_onshipping.py", line 398, in _simulate_invoice_line_onchange
    line._onchange_product_id()
  File "E:\odoo\OCB\addons\account_asset\models\account_invoice.py", line 106, in _onchange_product_id
    vals = super(AccountInvoiceLine, self)._onchange_product_id()
  File "E:\odoo\source\ocaaddons\account-analytic\product_analytic\models\account_invoice.py", line 30, in _onchange_product_id
    ana_account = ana_accounts[INV_TYPE_MAP[inv_type]]
KeyError: False

**Comment by pedrobaeza** [comment]
Which module? Which version? Steps to reproduce? If not enough information provided, how do you expect that this potential problem gets solved?
