### ISSUE TITLE
[12.0] Stock Picking Invoicing: El campo `invoice_line_ids` no existe

### ISSUE THREAD

**Issue by josepmy** [OCA/account-invoicing#727]
Hi,

Trying to install stock_picking_invoicing appear this error.
I have the stock picking invoice link installed.
I updated the database.

`Contexto del error:
Vista `stock.move.form.invoice_state`
[view_id: 1611, xml_id: n/a, model: stock.move, parent_id: 1458]
2020-06-08 16:17:09,547 1438 WARNING pro-preauto_ori odoo.modules.loading: Transient module states were reset
2020-06-08 16:17:09,549 1438 ERROR pro-preauto_ori odoo.modules.registry: Failed to load registry
Traceback (most recent call last):
  File "/opt/odoo12/12.0/odoo/odoo/models.py", line 1109, in _validate_fields
    check(self)
  File "/opt/odoo12/12.0/odoo/odoo/addons/base/models/ir_ui_view.py", line 351, in _check_xml
    self.postprocess_and_fields(view.model, view_doc, view.id)
  File "/opt/odoo12/12.0/odoo/odoo/addons/base/models/ir_ui_view.py", line 1111, in postprocess_and_fields
    self.raise_view_error(message, view_id)
  File "/opt/odoo12/12.0/odoo/odoo/addons/base/models/ir_ui_view.py", line 548, in raise_view_error
    raise ValueError(message)
ValueError: El campo `invoice_line_ids` no existe

Contexto del error:
Vista `stock.move.form.invoice_state`
[view_id: 1611, xml_id: n/a, model: stock.move, parent_id: 1458]`

**Comment by legalsylvain** [comment]
- did you tried in a fresh database ? maybe a custom view is removing the field...

**Comment by josepmy** [comment]
Into the stock.move model I "have invoice_line_id" not "invoice_line_ids", any hint? I'm fuzzed.

After pull the module and update stock picking invoice link the invoice_line_ids was updated correctly.
