### ISSUE TITLE
[13.0] [account_invoice_supplier_self_invoice] Problem in migration script.

### ISSUE THREAD

**Issue by lmmar-ic** [OCA/account-invoicing#946]
Hi, 

When execute the openupgrade process to 13.0, the process stop in this module, when run post-migration script:

2021-05-26 10:21:31,908 7615 INFO openupgrade OpenUpgrade: account_invoice_supplier_self_invoice: post-migration script called with version 12.0.1.0.0
2021-05-26 10:21:31,909 7615 ERROR openupgrade odoo.sql_db: bad query:
        UPDATE account_move am
        SET self_invoice_number = ai.self_invoice_number,
            set_self_invoice = ai.set_self_invoice
            can_self_invoice = ai.can_self_invoice
        FROM account_invoice ai
        WHERE ai.id = am.old_invoice_id and ai.self_invoice_number is not null
ERROR: syntax error at or near "can_self_invoice"
LINE 5:             can_self_invoice = ai.can_self_invoice
                    ^

2021-05-26 10:21:31,909 7615 ERROR openupgrade OpenUpgrade: Error after 0:00:00.000580 running
        UPDATE account_move am
        SET self_invoice_number = ai.self_invoice_number,
            set_self_invoice = ai.set_self_invoice
            can_self_invoice = ai.can_self_invoice
        FROM account_invoice ai
        WHERE ai.id = am.old_invoice_id and ai.self_invoice_number is not null
2021-05-26 10:21:31,909 7615 ERROR openupgrade OpenUpgrade: account_invoice_supplier_self_invoice: error in migration script account_invoice_supplier_self_invoice/migrations/13.0.1.0.0/post-migration.py: syntax error at or near "can_self_invoice"
LINE 5:             can_self_invoice = ai.can_self_invoice
                    ^

2021-05-26 10:21:31,909 7615 ERROR openupgrade OpenUpgrade: syntax error at or near "can_self_invoice"
LINE 5:             can_self_invoice = ai.can_self_invoice
                    ^

Traceback (most recent call last):
  File "/opt/OpenUpgrade/openupgrade/lib/python3.6/site-packages/openupgradelib/openupgrade.py", line 1875, in wrapped_function
    if use_env2 else cr, version)
  File "/opt/OpenUpgrade/other-addons/account_invoice_supplier_self_invoice/migrations/13.0.1.0.0/post-migration.py", line 16, in migrate
    WHERE ai.id = am.old_invoice_id and ai.self_invoice_number is not null""",
  File "/opt/OpenUpgrade/openupgrade/lib/python3.6/site-packages/openupgradelib/openupgrade.py", line 1336, in logged_query
    cr.execute(query, args)
  File "/opt/OpenUpgrade/odoo/sql_db.py", line 173, in wrapper
    return f(self, *args, **kwargs)
  File "/opt/OpenUpgrade/odoo/sql_db.py", line 250, in execute
    res = self._obj.execute(query, params)
psycopg2.ProgrammingError: syntax error at or near "can_self_invoice"
LINE 5:             can_self_invoice = ai.can_self_invoice
                    ^
2021-05-26 10:21:31,911 7615 ERROR openupgrade odoo.modules.loading: Error executing post migration script for module account_invoice_supplier_self_invoice
: syntax error at or near "can_self_invoice"
LINE 5:             can_self_invoice = ai.can_self_invoice
                    ^

2021-05-26 10:21:31,912 7615 ERROR openupgrade odoo.modules.registry: Failed to load registry
Traceback (most recent call last):
  File "/opt/OpenUpgrade/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/OpenUpgrade/odoo/modules/loading.py", line 484, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check, upg_registry)
  File "/opt/OpenUpgrade/odoo/modules/loading.py", line 368, in load_marked_modules
    upg_registry=upg_registry,
  File "/opt/OpenUpgrade/odoo/modules/loading.py", line 256, in load_module_graph
    migrations.migrate_module(package, 'post')
  File "/opt/OpenUpgrade/odoo/modules/migration.py", line 185, in migrate_module
    migrate(self.cr, installed_version)
  File "/opt/OpenUpgrade/openupgrade/lib/python3.6/site-packages/openupgradelib/openupgrade.py", line 1875, in wrapped_function
    if use_env2 else cr, version)
  File "/opt/OpenUpgrade/other-addons/account_invoice_supplier_self_invoice/migrations/13.0.1.0.0/post-migration.py", line 16, in migrate
    WHERE ai.id = am.old_invoice_id and ai.self_invoice_number is not null""",
  File "/opt/OpenUpgrade/openupgrade/lib/python3.6/site-packages/openupgradelib/openupgrade.py", line 1336, in logged_query
    cr.execute(query, args)
  File "/opt/OpenUpgrade/odoo/sql_db.py", line 173, in wrapper
    return f(self, *args, **kwargs)
  File "/opt/OpenUpgrade/odoo/sql_db.py", line 250, in execute

    res = self._obj.execute(query, params)
psycopg2.ProgrammingError: syntax error at or near "can_self_invoice"
LINE 5:             can_self_invoice = ai.can_self_invoice
                    ^

2021-05-26 10:21:31,912 7615 CRITICAL openupgrade odoo.service.server: Failed to initialize database `openupgrade`.
Traceback (most recent call last):
  File "/opt/OpenUpgrade/odoo/service/server.py", line 1190, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/opt/OpenUpgrade/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/OpenUpgrade/odoo/modules/loading.py", line 484, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check, upg_registry)
  File "/opt/OpenUpgrade/odoo/modules/loading.py", line 368, in load_marked_modules
    upg_registry=upg_registry,
  File "/opt/OpenUpgrade/odoo/modules/loading.py", line 256, in load_module_graph
    migrations.migrate_module(package, 'post')
  File "/opt/OpenUpgrade/odoo/modules/migration.py", line 185, in migrate_module
    migrate(self.cr, installed_version)
  File "/opt/OpenUpgrade/openupgrade/lib/python3.6/site-packages/openupgradelib/openupgrade.py", line 1875, in wrapped_function
    if use_env2 else cr, version)
  File "/opt/OpenUpgrade/other-addons/account_invoice_supplier_self_invoice/migrations/13.0.1.0.0/post-migration.py", line 16, in migrate
    WHERE ai.id = am.old_invoice_id and ai.self_invoice_number is not null""",
  File "/opt/OpenUpgrade/openupgrade/lib/python3.6/site-packages/openupgradelib/openupgrade.py", line 1336, in logged_query
    cr.execute(query, args)
  File "/opt/OpenUpgrade/odoo/sql_db.py", line 173, in wrapper
    return f(self, *args, **kwargs)
  File "/opt/OpenUpgrade/odoo/sql_db.py", line 250, in execute
    res = self._obj.execute(query, params)
psycopg2.ProgrammingError: syntax error at or near "can_self_invoice"
LINE 5:             can_self_invoice = ai.can_self_invoice
                    ^

**Comment by albariera** [comment]
Thank you for creating the issue. I am sorry for the mistake. I hope that this PR fixes the problem: #947
